# Generated by Django 5.1 on 2024-08-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_author_book_check_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='check_out',
            new_name='borrowed_by',
        ),
    ]
